name: "NextPVR"
guid: "9574ac10-bf23-49bc-949f-924f23cfa48f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-nextpvr.png"
version: "7"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Live TV plugin for NextPVR"
description: >
  Provides access to live TV, program guide, and recordings from NextPVR.

category: "LiveTV"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.NextPVR.dll"
changelog: |2-
  ### New features and improvements ###
  - chore: plugin images (#24) @h1dden-da3m0n
  - Increase sid security (#19) @emveepee

  ### Dependency updates ###
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#22) @dependabot

  ### CI & build changes ###
  - Update ci (#26) @h1dden-da3m0n
  - chore(ci): builds, releas drafter and more (#21) @h1dden-da3m0n

  ### Code or Repo Maintenance ###
  - remove jQuery and update to es6 (#25) @grafixeyehero
