name: "NextPVR"
guid: "9574ac10-bf23-49bc-949f-924f23cfa48f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-nextpvr.png"
version: "7"
targetAbi: "10.7.7.0"
framework: "net6.0"
overview: "Live TV plugin for NextPVR"
description: >
  Provides access to live TV, program guide, and recordings from NextPVR.

category: "LiveTV"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.NextPVR.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - Changes for 10.8 alpha2 (#31) @emveepee
  - Use System.Text.Json (#17) @daullmer
